# On a manager run : docker stack deploy --compose-file=mastodon_assets.yml mastodon_assets
# The volumes here must match the mastodon.yml file, it will pre-compile assets on deploy
# and be done before the mastodon stack comes up
version: '3.5'
services:
  s3sync_assets:
    image: elementar/s3-volume
    env_file: mastodon_env.production
    command: /public-assets s3://mybucket/public-assets
    volumes:
      - public-assets:/public-assets
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=false
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.labels.db == true
  s3sync_packs:
    image: elementar/s3-volume
    env_file: mastodon_env.production
    command: /public-packs s3://mybucket/public-packs
    volumes:
      - public-packs:/public-packs
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=false
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.labels.db == true
  precompile:
    image: tootsuite/mastodon:v2.4.4
    env_file: mastodon_env.production
    command: rails assets:precompile
    volumes:
      - public-assets:/mastodon/public/assets
      - public-packs:/mastodon/public/packs
    deploy:
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=false
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 20s
      placement:
        constraints:
          - node.labels.db == true
volumes:
  public-assets:
  public-packs:
  
